plugins {
    id 'com.android.application'
}

android {
    namespace 'com.qx.qylogsample'
    compileSdk 33
    ndkVersion '24.0.8215888'

    defaultConfig {
        applicationId 'com.qx.qylogsample'
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName '1.0'

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_shared'
            }
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
        }
    }
}

dependencies {
    implementation project(':qylog_sdk')
}
